#!/usr/bin/env python3
"""Build the root README skills catalog from repository skill metadata."""

from __future__ import annotations

import argparse
import codecs
import json
import os
import re
import sys
import tempfile
import unicodedata
from dataclasses import dataclass
from pathlib import Path


START_MARKER = "<!-- BEGIN GENERATED SKILLS INDEX -->"
END_MARKER = "<!-- END GENERATED SKILLS INDEX -->"
GIST_STATE_REL_PATH = "skills/documentation/auto-gist-publisher/state/published.json"
GENERATED_NOTICE = "<!-- Generated by sync-skills-readme. Do not edit inside these markers. -->"
SKILLS_HEADING = "## Skills"
CATEGORY_TERMS = {
    "ai": "AI",
    "api": "API",
    "ci": "CI",
    "cd": "CD",
    "github": "GitHub",
    "llm": "LLM",
    "llms": "LLMs",
    "mcp": "MCP",
    "ml": "ML",
    "qa": "QA",
    "seo": "SEO",
    "ui": "UI",
    "ux": "UX",
}


class CatalogError(RuntimeError):
    """Raised when repository metadata cannot produce a safe catalog."""


@dataclass(frozen=True)
class SkillEntry:
    category: str
    display_name: str
    name: str
    summary: str
    link: str
    gist_url: str | None = None


def _parse_scalar(value: str, source: Path, key: str) -> str:
    value = value.strip()
    if not value:
        return value
    if value[0] == '"':
        if len(value) < 2 or value[-1] != '"':
            raise CatalogError(f"{source}: unterminated quoted value for {key!r}")
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as exc:
            raise CatalogError(f"{source}: invalid quoted value for {key!r}") from exc
        if not isinstance(decoded, str):
            raise CatalogError(f"{source}: {key!r} must be a string")
        return decoded
    if value[0] == "'":
        if len(value) < 2 or value[-1] != "'":
            raise CatalogError(f"{source}: unterminated quoted value for {key!r}")
        inner = value[1:-1]
        if "'" in inner.replace("''", ""):
            raise CatalogError(f"{source}: invalid single-quoted value for {key!r}")
        return inner.replace("''", "'")
    if value[0] in "!&*[{>|":
        raise CatalogError(f"{source}: unsupported YAML value for {key!r}; use a string scalar")

    value = re.split(r"[ \t]+#", value, maxsplit=1)[0].rstrip()
    if re.search(r":[ \t]", value):
        raise CatalogError(f"{source}: quote {key!r} because it contains a colon followed by a space")
    if value.casefold() in {"null", "~", "true", "false", "yes", "no", "on", "off"}:
        raise CatalogError(f"{source}: {key!r} must be a string, not a YAML reserved scalar")
    return value


def _parse_frontmatter(text: str, source: Path) -> tuple[dict[str, str], int]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise CatalogError(f"{source}: missing opening YAML frontmatter marker")

    try:
        end = next(index for index in range(1, len(lines)) if lines[index].strip() == "---")
    except StopIteration as exc:
        raise CatalogError(f"{source}: missing closing YAML frontmatter marker") from exc

    values: dict[str, str] = {}
    index = 1
    while index < end:
        line = lines[index]
        if not line.strip() or line.lstrip().startswith("#") or line[:1].isspace():
            index += 1
            continue
        if ":" not in line:
            index += 1
            continue

        key, raw_value = line.split(":", 1)
        key = key.strip()
        raw_value = raw_value.strip()

        if raw_value in {">", ">-", ">+", "|", "|-", "|+"}:
            if key in values:
                raise CatalogError(f"{source}: duplicate frontmatter key {key!r}")
            block_lines: list[str] = []
            index += 1
            while index < end and (not lines[index].strip() or lines[index][:1].isspace()):
                block_lines.append(lines[index].strip())
                index += 1
            separator = " " if raw_value.startswith(">") else "\n"
            values[key] = separator.join(block_lines).strip()
            continue

        if key in values:
            raise CatalogError(f"{source}: duplicate frontmatter key {key!r}")
        values[key] = _parse_scalar(raw_value, source, key)
        index += 1

    return values, end


def _yaml_scalar(text: str, key: str, source: Path) -> str | None:
    matches = re.findall(rf"(?m)^[ \t]*{re.escape(key)}:[ \t]*(.*?)[ \t]*$", text)
    if not matches:
        return None
    if len(matches) > 1:
        raise CatalogError(f"{source}: duplicate metadata key {key!r}")
    value = _parse_scalar(matches[0], source, key)
    return value or None


def _first_heading(lines: list[str], start: int) -> str | None:
    for line in lines[start:]:
        match = re.match(r"^#\s+(.+?)\s*$", line)
        if match:
            return match.group(1).strip()
    return None


def _first_sentence(value: str) -> str:
    normalized = " ".join(value.split())
    match = re.match(r"^(.+?[.!?])(?:\s|$)", normalized)
    return match.group(1) if match else normalized


def _category_title(slug: str) -> str:
    words = [CATEGORY_TERMS.get(word, word) for word in slug.split("-")]
    if words and words[0] not in CATEGORY_TERMS.values():
        words[0] = words[0].capitalize()
    return " ".join(words)


def _punctuate(value: str) -> str:
    value = " ".join(value.split()).strip()
    return value if value.endswith((".", "!", "?")) else f"{value}."


def _markdown_text(value: str) -> str:
    return value.replace("\\", "\\\\").replace("[", "\\[").replace("]", "\\]")


def _collision_key(value: str) -> str:
    return unicodedata.normalize("NFKC", value).casefold()


def _contains_symlink(path: Path, stop: Path) -> bool:
    current = path
    while current != stop:
        if current.is_symlink():
            return True
        current = current.parent
    return False


def _load_gist_urls(repo_root: Path) -> dict[str, str]:
    """Map `category/skill-folder` keys to published gist URLs.

    Reads the auto-gist-publisher state file. A missing file yields no URLs;
    malformed JSON is a hard error because the catalog would silently drop
    gist badges otherwise.
    """
    state_file = repo_root / GIST_STATE_REL_PATH
    if not state_file.is_file():
        return {}
    try:
        data = json.loads(state_file.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeError) as exc:
        raise CatalogError(f"{state_file}: invalid gist state JSON") from exc
    published = data.get("published", {}) if isinstance(data, dict) else None
    if not isinstance(published, dict):
        raise CatalogError(f"{state_file}: 'published' must be an object")
    urls: dict[str, str] = {}
    for key, entry in published.items():
        if not isinstance(entry, dict):
            continue
        url = entry.get("gist_url")
        if isinstance(url, str) and url.startswith("https://gist.github.com/"):
            urls[key] = url
    return urls


def collect_skills(repo_root: Path) -> list[SkillEntry]:
    skills_root = repo_root / "skills"
    if not skills_root.is_dir():
        raise CatalogError(f"{skills_root}: skills directory not found")

    all_skill_files = sorted(skills_root.rglob("SKILL.md"))
    skill_files = sorted(skills_root.glob("*/*/SKILL.md"))
    unexpected = [skill_file for skill_file in all_skill_files if skill_file not in skill_files]
    if unexpected:
        paths = ", ".join(str(path) for path in unexpected)
        raise CatalogError(f"{skills_root}: SKILL.md files must be exactly two folders deep: {paths}")
    if not skill_files:
        raise CatalogError(f"{skills_root}: no skills found at <category>/<skill>/SKILL.md")

    gist_urls = _load_gist_urls(repo_root)

    entries: list[SkillEntry] = []
    names: dict[str, str] = {}
    for skill_file in skill_files:
        relative = skill_file.relative_to(skills_root)
        category_slug, folder_name, _ = relative.parts
        if _contains_symlink(skill_file, skills_root):
            raise CatalogError(f"{skill_file}: symlinked skill paths are not supported")
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", category_slug):
            raise CatalogError(f"{skill_file}: category folder must use lowercase kebab-case")
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", folder_name):
            raise CatalogError(f"{skill_file}: skill folder must use lowercase kebab-case")
        text = skill_file.read_text(encoding="utf-8")
        frontmatter, frontmatter_end = _parse_frontmatter(text, skill_file)

        name = frontmatter.get("name", "").strip()
        description = frontmatter.get("description", "").strip()
        if not name or not description:
            raise CatalogError(f"{skill_file}: frontmatter requires non-empty name and description")
        if name != folder_name:
            raise CatalogError(
                f"{skill_file}: skill name {name!r} must match folder {folder_name!r}"
            )
        collision_key = _collision_key(name)
        if collision_key in names:
            raise CatalogError(
                f"{skill_file}: skill name {name!r} collides with {names[collision_key]!r}"
            )
        names[collision_key] = name

        agent_metadata = skill_file.parent / "agents" / "openai.yaml"
        agent_text = agent_metadata.read_text(encoding="utf-8") if agent_metadata.is_file() else ""
        heading = _first_heading(text.splitlines(), frontmatter_end + 1)
        display_name = (
            _yaml_scalar(agent_text, "display_name", agent_metadata)
            or heading
            or name.replace("-", " ").title()
        )
        summary = _yaml_scalar(agent_text, "short_description", agent_metadata) or _first_sentence(description)

        entries.append(
            SkillEntry(
                category=_category_title(category_slug),
                display_name=_markdown_text(" ".join(display_name.split())),
                name=name,
                summary=_markdown_text(_punctuate(summary)),
                link=skill_file.relative_to(repo_root).as_posix(),
                gist_url=gist_urls.get(f"{category_slug}/{folder_name}"),
            )
        )

    return sorted(entries, key=lambda entry: (entry.category.casefold(), entry.display_name.casefold(), entry.name))


def render_catalog(entries: list[SkillEntry]) -> str:
    lines: list[str] = []
    current_category: str | None = None
    for entry in entries:
        if entry.category != current_category:
            if lines:
                lines.append("")
            lines.extend([f"### {entry.category}", ""])
            current_category = entry.category
        line = f"- [{entry.display_name}]({entry.link}) — {entry.summary}"
        if entry.gist_url:
            line += f" [gist ↗]({entry.gist_url})"
        lines.append(line)
    return "\n".join(lines)


def update_readme(original: str, catalog: str) -> str:
    start_count = original.count(START_MARKER)
    end_count = original.count(END_MARKER)
    block = f"{START_MARKER}\n{GENERATED_NOTICE}\n\n{catalog}\n\n{END_MARKER}"

    if start_count != end_count or start_count > 1:
        raise CatalogError("README.md: generated catalog markers are missing or duplicated")

    heading_matches = list(
        re.finditer(rf"(?m)^{re.escape(SKILLS_HEADING)}[ \t]*$", original)
    )
    if len(heading_matches) > 1:
        raise CatalogError("README.md: duplicate Skills headings are not supported")
    heading_match = heading_matches[0] if heading_matches else None

    if start_count == 1:
        start = original.index(START_MARKER)
        end_start = original.index(END_MARKER)
        if end_start < start:
            raise CatalogError("README.md: generated catalog markers are reversed")
        if not heading_match:
            raise CatalogError("README.md: generated catalog requires a Skills heading")
        following = original[heading_match.end() :]
        next_heading = re.search(r"(?m)^##[ \t]+", following)
        section_end = heading_match.end() + (
            next_heading.start() if next_heading else len(following)
        )
        if start < heading_match.end() or end_start >= section_end:
            raise CatalogError("README.md: generated catalog markers must be inside the Skills section")
        end = end_start + len(END_MARKER)
        return f"{original[:start]}{block}{original[end:]}"

    if not heading_match:
        return f"{original.rstrip()}\n\n{SKILLS_HEADING}\n\n{block}\n"

    following = original[heading_match.end() :]
    next_heading = re.search(r"(?m)^##[ \t]+", following)
    section_end = heading_match.end() + (next_heading.start() if next_heading else len(following))
    tail = original[section_end:]
    replacement = f"{original[:heading_match.end()]}\n\n{block}"
    if tail:
        return f"{replacement}\n\n{tail.lstrip(chr(10))}"
    return f"{replacement}\n"


def _decode_readme(data: bytes, source: Path) -> tuple[str, str, bool]:
    has_bom = data.startswith(codecs.BOM_UTF8)
    payload = data[len(codecs.BOM_UTF8) :] if has_bom else data
    crlf_count = payload.count(b"\r\n")
    bare_lf_count = payload.count(b"\n") - crlf_count
    if crlf_count and bare_lf_count:
        raise CatalogError(f"{source}: mixed LF and CRLF line endings are not supported")
    newline = "\r\n" if crlf_count else "\n"
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise CatalogError(f"{source}: README must be UTF-8") from exc
    return text.replace("\r\n", "\n"), newline, has_bom


def _encode_readme(text: str, newline: str, has_bom: bool) -> bytes:
    payload = text.replace("\n", newline).encode("utf-8")
    return codecs.BOM_UTF8 + payload if has_bom else payload


def _atomic_write(path: Path, data: bytes) -> None:
    mode = path.stat().st_mode & 0o7777
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(dir=path.parent, prefix=f".{path.name}.", delete=False) as handle:
            temporary_name = handle.name
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_name, mode)
        os.replace(temporary_name, path)
    finally:
        if temporary_name and os.path.exists(temporary_name):
            os.unlink(temporary_name)


def sync(repo_root: Path, write: bool = False) -> int:
    repo_root = repo_root.resolve()
    readme = repo_root / "README.md"
    if not readme.is_file():
        raise CatalogError(f"{readme}: README not found")

    original_bytes = readme.read_bytes()
    original, newline, has_bom = _decode_readme(original_bytes, readme)
    updated = update_readme(original, render_catalog(collect_skills(repo_root)))
    updated_bytes = _encode_readme(updated, newline, has_bom)
    if updated_bytes == original_bytes:
        print("README.md skills catalog is current.")
        return 0
    if not write:
        print("README.md skills catalog is stale. Run the generator with --write.", file=sys.stderr)
        return 1

    _atomic_write(readme, updated_bytes)
    print("Updated README.md skills catalog.")
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="Repository containing README.md and skills/ (default: current directory).",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="Return 1 when README.md would change; never write files (default).",
    )
    mode.add_argument(
        "--write",
        action="store_true",
        help="Update README.md atomically when the generated catalog changed.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        return sync(args.repo_root, write=args.write)
    except (CatalogError, OSError, UnicodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
